language: python

python: "3.6"

git:
  depth: 1

env:
  -DJANGO=3.1.2 DB=mysql


install:
  - pip install -r requirements.txt

script:
  - coverage run manage.py test

after_script:
  - bash <(curl -s https://codecov.io/bash)
