# Generated by Django 3.1 on 2020-09-17 19:10
"""Add end date in Django polls application."""
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    """Migration class for this file."""

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now,
                                       verbose_name='Date that polls expires'),
            preserve_default=False,
        ),
    ]
